resolver: ghc-8.2.1
packages:
- inline-c
- inline-c-cpp
- sample-cabal-project
extra-deps:
- QuickCheck-2.10.0.1
- ansi-wl-pprint-0.6.8
- hashable-1.2.6.1
- mtl-2.2.1
- parsec-3.1.11
- parsers-0.12.5
- unordered-containers-0.2.8.0
- vector-0.12.0.1
- ansi-terminal-0.6.3.1
- attoparsec-0.13.1.0
- base-orphans-0.6
- cabal-doctest-1.0.2
- charset-0.3.7.1
- primitive-0.6.2.0
- random-1.1
- scientific-0.3.5.1
- text-1.2.2.2
- tf-random-0.5
- integer-logarithms-1.0.2
- semigroups-0.18.3
# for tests
- hspec-2.4.4
- raw-strings-qq-1.1
- regex-posix-0.95.2
- HUnit-1.6.0.0
- call-stack-0.1.0
- hspec-core-2.4.4
- hspec-discover-2.4.4
- hspec-expectations-0.8.2
- regex-base-0.93.2
- async-2.1.1.1
- quickcheck-io-0.2.0
- setenv-0.1.1.3
- stm-2.4.4.1
- safe-exceptions-0.1.6.0
- exceptions-0.8.3
- transformers-compat-0.5.1.4
